### GET - Listar todos os pacientes
GET http://localhost:8080/api/pacientes



### POST - Criar novo paciente
POST http://localhost:8080/api/pacientes
Content-Type: application/json

{
  "nome": "Maria da Silva",
  "endereco": "Rua das Flores, 45",
  "idade": 78,
  "telefoneEmergencia": "(47) 99999-1234",
  "estadoEmocionalAtual": "FELIZ",
  "atividades": [],
  "historico": [],
  "album": null
}


### PUT - Atualizar paciente (id = 1)
PUT http://localhost:8080/api/pacientes/1
Content-Type: application/json

{
  "nome": "Maria Atualizada",
  "endereco": "Av. Brasil, 999",
  "idade": 79,
  "telefoneEmergencia": "(47) 98888-4321",
  "estadoEmocionalAtual": "TRISTE",
  "atividades": [],
  "historico": [],
  "album": null
}


### DELETE - Excluir paciente (id = 1)
DELETE http://localhost:8080/api/v1/pacientes/1
